#!groovy
import hudson.EnvVars
import jenkins.model.*

node {
    stage('Fetch'){
        checkout ( [$class: 'GitSCM',
        branches: [[name: 'master' ]],
        userRemoteConfigs: [[
            url: 'https://github.com/hussopa/jenkins-poc-sw/']]])
    }
    
    stage('Bisect'){
        def search = (params.search == 'bisect') ? "bisect_$currentBuild.number" : params.search
        gitbisect badEndCommit: "$params.badEndCommit", 
            continuesBuild: true, 
            gitCommand: 'git', 
            goodStartCommit: "$params.goodStartCommit", 
            jobToRun: 'build', 
            minSuccessfulIterations: 1, 
            overrideGitCommand: false, 
            retryCount: 0, 
            revisionParameterName: 'REVISION', 
            searchIdentifier: search
    }
    
}
