#!groovy
import hudson.EnvVars
import jenkins.model.*


class G{
    static String FIRST = "SILLY"
    static String SECOND = "LITTLE"
    static String THIRD = "STRING"
}

node {
    
    stage("SCM") {
        def branch = params.REVISION ?: 'master'
        checkout ( [$class: 'GitSCM',
        branches: [[name: branch ]],
        userRemoteConfigs: [[
            url: 'https://github.com/hussopa/env_test/']]])
    }
    
    withEnv(["SILLY=${G.FIRST}", "LITTLE=${G.SECOND}", "STRING=${G.THIRD}"]) {
        stage('Build'){
            sh "python py_file.py"
        }
    }
}