#!groovy
import hudson.EnvVars
import jenkins.model.*

node {
    
    stage("SCM") {
        def branch = params.REVISION ?: 'master'
        checkout ( [$class: 'GitSCM',
        branches: [[name: branch ]],
        userRemoteConfigs: [[
            url: 'https://github.com/hussopa/jenkins-poc/']]])
    }
    
    stage('test'){
    echo "Hello World + $params.REVISION"
    currentBuild.result = 'UNSTABLE'
    currentBuild.description = "$params.REVISION"
    }
}
