#!groovy
import hudson.EnvVars
import jenkins.model.*

node {
    
    stage("SCM") {
        def branch = params.REVISION ?: 'master'
        checkout ( [$class: 'GitSCM',
        branches: [[name: branch ]],
        userRemoteConfigs: [[
            url: 'https://github.com/hussopa/jenkins-poc-sw/']]])
    }

    stage("Get Artifacts") {
        copyArtifacts(projectName: "$params.build_job", 
                    selector: specific("$params.build_number"),
                    target: "./output")
    }
    
    stage('Run test'){
        currentBuild.description = "$params.build_job/#$params.build_number"
        def testName = params.test_name ?: 'test.robot' 
            dir("tests") {
                sh "robot " + testName
            }
    }
}
