#!groovy
import hudson.EnvVars
import jenkins.model.*

node {
    
    stage("SCM") {
        def branch = params.REVISION ?: 'master'
        checkout ( [$class: 'GitSCM',
        branches: [[name: branch ]],
        userRemoteConfigs: [[
            url: 'https://github.com/hussopa/jenkins-poc/']]])
    }

    stage("Get Artifacts") {

    }
    
    stage('Run test'){
        def testName = params.test_name ?: 'test.robot' 
            dir("../tests") {
                sh "ls"
                sh "robot " + testName
            }
    }
}
